let isi = "Semangat...";
console.log(isi.repeat(5));
console.log("----------------------------------------------------");
console.log('*****'.repeat(1));
console.log('*****'.repeat(4));
console.log('*****'.repeat(8));
console.log('*****'.repeat(12));
console.log('*****'.repeat(16));
console.log('*****'.repeat(12));
console.log('*****'.repeat(8));
console.log('*****'.repeat(4));
console.log('*****'.repeat(1));